name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject API Key
        run: |
          # Replaces the empty string in the process shim with your secret
          sed -i "s/API_KEY: \"\"/API_KEY: \"${{ secrets.API_KEY }}\"/g" index.html
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4